"""create multiple index

Revision ID: d4c019702668
Revises: 852d0134f0ad
Create Date: 2018-02-01 16:42:56.866754

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4c019702668'
down_revision = '852d0134f0ad'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    conn.execute("CREATE INDEX SAMPLE_CURR_ALPHA_ANALYSIS_INDEX ON SAMPLE (CURR_ALPHA_ANALYSIS);")
    conn.execute("CREATE INDEX ANALYSIS_SAMPLE_ID_INDEX ON ANALYSIS (SAMPLE_ID);")
    conn.execute("CREATE INDEX MAP_ANALYSIS_ANALYSIS_ID_INDEX ON MAP_ANALYSIS (ANALYSIS_ID);")
    conn.execute("CREATE INDEX ANALYSIS_COMMENT_ANALYSIS_ID_INDEX ON ANALYSIS_COMMENT (ANALYSIS_ID);")
    conn.execute("CREATE INDEX MAP_ANALYSIS_JUNCTIONS_JUNCTION_ID_INDEX ON MAP_ANALYSIS_JUNCTIONS (JUNCTION_ID);")
    conn.execute(
        "CREATE INDEX MAP_ANALYSIS_JUNCTIONS_MAP_ANALYSIS_ID_INDEX ON MAP_ANALYSIS_JUNCTIONS (MAP_ANALYSIS_ID);")
    conn.execute("CREATE INDEX REQUEST_COMMENT_REQUEST_ID_INDEX ON REQUEST_COMMENT (REQUEST_ID);")
    conn.execute("CREATE INDEX OBSERVED_MAP_COMMENT_OBSERVED_MAP_ID_INDEX ON OBSERVED_MAP_COMMENT (OBSERVED_MAP_ID);")
    conn.execute("CREATE INDEX OBSERVED_MAP_MAP_ID_INDEX ON OBSERVED_MAP (MAP_ID);")


def downgrade():
    conn = op.get_bind()
    conn.execute("DROP INDEX SAMPLE_CURR_ALPHA_ANALYSIS_INDEX ON SAMPLE;")
    conn.execute("DROP INDEX ANALYSIS_SAMPLE_ID_INDEX ON ANALYSIS;")
    conn.execute("DROP INDEX MAP_ANALYSIS_ANALYSIS_ID_INDEX ON MAP_ANALYSIS;")
    conn.execute("DROP INDEX ANALYSIS_COMMENT_ANALYSIS_ID_INDEX ON ANALYSIS_COMMENT;")
    conn.execute("DROP INDEX MAP_ANALYSIS_JUNCTIONS_JUNCTION_ID_INDEX ON MAP_ANALYSIS_JUNCTIONS;")
    conn.execute(
        "DROP INDEX MAP_ANALYSIS_JUNCTIONS_MAP_ANALYSIS_ID_INDEX ON MAP_ANALYSIS_JUNCTIONS;")
    conn.execute("DROP INDEX REQUEST_COMMENT_REQUEST_ID_INDEX ON REQUEST_COMMENT;")
    conn.execute("DROP INDEX OBSERVED_MAP_COMMENT_OBSERVED_MAP_ID_INDEX ON OBSERVED_MAP_COMMENT;")
    conn.execute("DROP INDEX OBSERVED_MAP_MAP_ID_INDEX ON OBSERVED_MAP;")
